/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>




void configureIO();
void dark(char i);
void light(char i);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	configureIO();
	_Bool reset = false;
	_Bool pressed = false;

	char c = 0;

	for( char i = 0;i<9;){

		if (reset){
			c = 0;
			dark(1);
			dark(2);
		}

		else if (c<5 && pressed){
			pressed = false;
			c++;
		}

		else if (c == 1){
			light(1);
		}

		else if (c == 5){
			light(2);
		}


	}
}

void configureIO(){

}


void light (char i){

	switch (i){
			case 1:            break;
			case 2:            break;
			default: break;
		}

}



void dark (char i){

	switch (i){
		case 1:            break;
		case 2:            break;
		default: break;
	}

}


